/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-06-28 18:57:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.Random;

public final class AddTravel0_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Random");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("    <HEAD>\r\n");
      out.write("\r\n");
      out.write("    <script LANGUAGE=\"Javascript\" SRC=\"Images/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <LINK href=\"styles.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("    <script LANGUAGE=\"Javascript\" SRC=\"Images/calender.js\"></script>\r\n");
      out.write("    <script LANGUAGE=\"Javascript\" >\r\n");
      out.write("		function ChkMandatoryField(F,T){\r\n");
      out.write("			var val= F.value;\r\n");
      out.write("			if(val==\"\"){alert(T+\" is mandatory\");return false;}\r\n");
      out.write("		}\r\n");
      out.write("		function ChkNumField(F,T){\r\n");
      out.write("			var val = F.value;\r\n");
      out.write("			if(isNaN(val)==true||val==\"\"){alert(\"Please enter numbers for \"+T);return false;}\r\n");
      out.write("		}\r\n");
      out.write("		function ChkAlphaNumericField(F,T){\r\n");
      out.write("			var val = F.value;\r\n");
      out.write("			var pattern = /^([a-zA-Z0-9]{1,250})$/;\r\n");
      out.write("			if(!(pattern.test(val)==true)){alert(\"Please enter alphabets or numbers for \"+T);return false;}\r\n");
      out.write("		}\r\n");
      out.write("		function ChkAlphaField(F,T){\r\n");
      out.write("			var val = F.value;\r\n");
      out.write("			var pattern = /^([a-zA-Z ]{1,250})$/;\r\n");
      out.write("			if(!(pattern.test(val)==true)){alert(\"Please enter text for \"+T);return false;}\r\n");
      out.write("		}\r\n");
      out.write("		function ChkEmailField(F,T){\r\n");
      out.write("			var val = F.value;\r\n");
      out.write("			var pattern = /^([a-zA-Z0-9\\_\\.]{4,25})$/;\r\n");
      out.write("			if(!(pattern.test(val)==true)){alert(\"Please enter valid email for \"+T);return false;}\r\n");
      out.write("		}\r\n");
      out.write("		function ChkDateField(F,T)\r\n");
      out.write("		{\r\n");
      out.write("			var val = F.value;\r\n");
      out.write("		    var pattern = /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/;\r\n");
      out.write("		    if(!(pattern.test(val)==true)){alert(\"Please enter valid date format (yyyy-mm-dd) for \"+T);return false;}\r\n");
      out.write("		}\r\n");
      out.write("		function validate()\r\n");
      out.write("		{\r\n");
      out.write("			var frm = document.forms(0);\r\n");
      out.write("			if(ChkMandatoryField(frm.Travels,'Travels Name')==false) return false;\r\n");
      out.write("			if(ChkMandatoryField(frm.Location,'Location')==false) return false;\r\n");
      out.write("			if(ChkAlphaField(frm.Location,'Location')==false) return false;\r\n");
      out.write("			if(ChkMandatoryField(frm.Address,'Address')==false) return false;\r\n");
      out.write("			if(ChkMandatoryField(frm.AgentName,'Agent Name')==false) return false;\r\n");
      out.write("			if(ChkMandatoryField(frm.PhoneNumber,'Phone Number')==false) return false;\r\n");
      out.write("			if(ChkNumField(frm.PhoneNumber,'Phone Number')==false) return false;\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	</HEAD>\r\n");
      out.write("	<Body class=SC>\r\n");
      out.write("<HR>\r\n");
      out.write("<B><FONT COLOR=\"#CC00CC\" face='verdana'>Add New Travel</FONT></B>\r\n");
      out.write("<HR>	\r\n");

	Integer IAuth =(Integer)session.getAttribute("auth");
    System.out.println (" IAuth is " + IAuth);
	int auth=-1;
	if(IAuth!=null){ auth= IAuth.intValue();}
	System.out.println("===Authentication=="+auth);
auth=0;
if(auth!=0){
	
      out.write("<P align=center><IMG SRC=\"Images/error.gif\" WIDTH=\"17\" HEIGHT=\"13\" BORDER=\"0\" ALT=\"\"><B><FONT COLOR=\"red\">You are not authorized to access this page</FONT></B></P>");

}
else{

      out.write("\r\n");
      out.write("<FORM ACTION=\"AddTravels1.jsp\" onsubmit=\"return validate()\">\r\n");
      out.write("	<center>\r\n");
      out.write("   <TABLE BORDER=\"0\" CELLSPACING=\"2\"  CELLPADDING=\"2\" >\r\n");
      out.write("	   <TR class=row_title  ALIGN=\"center\">\r\n");
      out.write("	   <TH COLSPAN=\"2\"> Add New Travel </TH>\r\n");
      out.write("		<tr class=\"row_odd\">\r\n");
      out.write("			<td>Travels Name<FONT COLOR=\"red\">*</FONT></td>\r\n");
      out.write("				<TD><Input type=text name='Travels' value=''></TD>\r\n");
      out.write("		</TR>\r\n");
      out.write("		<tr class=\"row_even\">\r\n");
      out.write("			<td>Location<FONT COLOR=\"red\">*</FONT></td>\r\n");
      out.write("				<td><SELECT NAME=\"Location\" class=\"ListBox\">\r\n");
      out.write("				<option value=\"A.S.Peta\">A.S.Peta</option>\r\n");
      out.write("				<option value=\"Ahmedabad\">Ahmedabad</option>\r\n");
      out.write("				<option value=\"Amalapuram\">Amalapuram</option>\r\n");
      out.write("				<option value=\"Ambaji\">Ambaji       </option>\r\n");
      out.write("				<option value=\"Anakapalli\">Anakapalli</option>\r\n");
      out.write("				<option value=\"Anantapur\">Anantapur</option>\r\n");
      out.write("				<option value=\"Annavaram\">Annavaram</option>\r\n");
      out.write("				<option value=\"Atmakur\">Atmakur</option>\r\n");
      out.write("				<option value=\"Aurangabad\">Aurangabad </option>\r\n");
      out.write("				<option value=\"Bangalore\">Bangalore</option>\r\n");
      out.write("				<option value=\"Bapatla\">Bapatla</option>\r\n");
      out.write("				<option value=\"Bhopal\">Bhopal</option>\r\n");
      out.write("				<option value=\"Bhuj\">Bhuj</option>\r\n");
      out.write("				<option value=\"Chandigarh\">Chandigarh </option>\r\n");
      out.write("				<option value=\"Chennai\">Chennai</option>\r\n");
      out.write("				<option value=\"Chilakaluripet\">Chilakaluripet</option>\r\n");
      out.write("				<option value=\"Chirala\">Chirala</option>\r\n");
      out.write("				<option value=\"Cochin\">Cochin</option>\r\n");
      out.write("				<option value=\"Delhi\">Delhi</option>\r\n");
      out.write("				<option value=\"Devarpalli\">Devarpalli</option>\r\n");
      out.write("				<option value=\"Gandhidham\">Gandhidham </option>\r\n");
      out.write("				<option value=\"Goa\">Goa</option>\r\n");
      out.write("				<option value=\"Gokavaram\">Gokavaram</option>\r\n");
      out.write("				<option value=\"Guduru\">Guduru</option>\r\n");
      out.write("				<option value=\"Guntur\">Guntur</option>\r\n");
      out.write("				<option value=\"Hubli\">Hubli</option>\r\n");
      out.write("				<option selected=\"selected\" value=\"Hyderabad\">Hyderabad</option>\r\n");
      out.write("				<option value=\"Indore\">Indore </option>\r\n");
      out.write("				<option value=\"Inkollu\">Inkollu</option>\r\n");
      out.write("				<option value=\"Jaggampet\">Jaggampet</option>\r\n");
      out.write("				<option value=\"Jaipur\">Jaipur</option>\r\n");
      out.write("				<option value=\"Jammu\">Jammu</option>\r\n");
      out.write("				<option value=\"Jamnagar\">Jamnagar </option>\r\n");
      out.write("				<option value=\"Jangareddy Gudem\">Jangareddy Gudem</option>\r\n");
      out.write("				<option value=\"Kadapa\">Kadapa</option>\r\n");
      out.write("				<option value=\"Kakinada\">Kakinada</option>\r\n");
      out.write("				<option value=\"Kaligiri\">Kaligiri</option>\r\n");
      out.write("				<option value=\"Karimnagar\">Karimnagar</option>\r\n");
      out.write("				<option value=\"Kathipudi\">Kathipudi</option>\r\n");
      out.write("				<option value=\"Katra\">Katra </option>\r\n");
      out.write("				<option value=\"Kavali\">Kavali</option>\r\n");
      out.write("				<option value=\"Kolhapur\">Kolhapur </option>\r\n");
      out.write("				<option value=\"Kovvuru\">Kovvuru</option>\r\n");
      out.write("				<option value=\"Kurnool\">Kurnool</option>\r\n");
      out.write("				<option value=\"Mahabaleshwar\">Mahabaleshwar</option>\r\n");
      out.write("				<option value=\"Mahabalipuram\">Mahabalipuram </option>\r\n");
      out.write("				<option value=\"Manali\">Manali </option>\r\n");
      out.write("				<option value=\"Mangalore\">Mangalore </option>\r\n");
      out.write("				<option value=\"MountAbu\">MountAbu</option>\r\n");
      out.write("				<option value=\"Mumbai\">Mumbai</option>\r\n");
      out.write("				<option value=\"Naidupeta\">Naidupeta</option>\r\n");
      out.write("				<option value=\"Narasaraopet\">Narasaraopet</option>\r\n");
      out.write("				<option value=\"Nasik\">Nasik</option>\r\n");
      out.write("				<option value=\"Nellore\">Nellore</option>\r\n");
      out.write("				<option value=\"Ongole\">Ongole</option>\r\n");
      out.write("				<option value=\"Palitana\">Palitana </option>\r\n");
      out.write("				<option value=\"Pangidi\">Pangidi</option>\r\n");
      out.write("				<option value=\"Peddapuram\">Peddapuram</option>\r\n");
      out.write("				<option value=\"Ponnur\">Ponnur</option>\r\n");
      out.write("				<option value=\"Pune\">Pune</option>\r\n");
      out.write("				<option value=\"Railway Koduru\">Railway Koduru</option>\r\n");
      out.write("				<option value=\"Raja Nagaram\">Raja Nagaram</option>\r\n");
      out.write("				<option value=\"Rajampet\">Rajampet</option>\r\n");
      out.write("				<option value=\"Rajamundry\">Rajamundry</option>\r\n");
      out.write("				<option value=\"Rajkot\">Rajkot</option>\r\n");
      out.write("				<option value=\"Rangampeta\">Rangampeta</option>\r\n");
      out.write("				<option value=\"Razole\">Razole</option>\r\n");
      out.write("				<option value=\"S.Konda\">S.Konda</option>\r\n");
      out.write("				<option value=\"Samarla Kota\">Samarla Kota</option>\r\n");
      out.write("				<option value=\"Sathenpalli\">Sathenpalli</option>\r\n");
      out.write("				<option value=\"Shiridi\">Shiridi</option>\r\n");
      out.write("				<option value=\"Shreenathji\">Shreenathji </option>\r\n");
      out.write("				<option value=\"Srikakulam\">Srikakulam</option>\r\n");
      out.write("				<option value=\"Srinagar\">Srinagar </option>\r\n");
      out.write("				<option value=\"Sullurupeta\">Sullurupeta</option>\r\n");
      out.write("				<option value=\"Surat\">Surat</option>\r\n");
      out.write("				<option value=\"Tenali\">Tenali</option>\r\n");
      out.write("				<option value=\"Thrissur\">Thrissur </option>\r\n");
      out.write("				<option value=\"Tiruchirapally\">Tiruchirapally </option>\r\n");
      out.write("				<option value=\"Tirupathi\">Tirupathi</option>\r\n");
      out.write("				<option value=\"Tuni\">Tuni</option>\r\n");
      out.write("				<option value=\"Udaipur\">Udaipur</option>\r\n");
      out.write("				<option value=\"Ujjain\">Ujjain</option>\r\n");
      out.write("				<option value=\"Ulavapadu\">Ulavapadu</option>\r\n");
      out.write("				<option value=\"Vadodara\">Vadodara</option>\r\n");
      out.write("				<option value=\"Vetapalem\">Vetapalem</option>\r\n");
      out.write("				<option value=\"Vijayanagaram\">Vijayanagaram</option>\r\n");
      out.write("				<option value=\"Vijayawada\">Vijayawada</option>\r\n");
      out.write("				<option value=\"Vinjamoor\">Vinjamoor</option>\r\n");
      out.write("				<option value=\"Vizag\">Vizag</option>\r\n");
      out.write("				<option value=\"Warangal\">Warangal</option>\r\n");
      out.write("\r\n");
      out.write("			</select>\r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"row_odd\">\r\n");
      out.write("			<td>Address<FONT COLOR=\"red\">*</FONT></td>\r\n");
      out.write("				<TD><textarea name=Address></textarea></TD>\r\n");
      out.write("		</TR>\r\n");
      out.write("		<tr class=\"row_even\">\r\n");
      out.write("			<td>Agent Name<FONT COLOR=\"red\">*</FONT></td>\r\n");
      out.write("				<TD><Input type=text name='AgentName' value=''></TD>\r\n");
      out.write("		</TR>\r\n");
      out.write("		<tr class=\"row_odd\">\r\n");
      out.write("			<td>Phone Number<FONT COLOR=\"red\">*</FONT></td>\r\n");
      out.write("				<TD><Input type=text name='PhoneNumber' value=''></TD>\r\n");
      out.write("		</TR>\r\n");
      out.write("		<TR><TH><INPUT TYPE=\"submit\" value='Submit'></TH><TH><INPUT TYPE=\"reset\" value='Clear'></TH></TR>\r\n");
      out.write("	</TABLE>\r\n");
      out.write("	<H6 align=center>Fields with <FONT SIZE=\"\" COLOR=\"red\">*</FONT> are mandatory </H6>\r\n");
      out.write("	</FORM>\r\n");
      out.write("	</BODY>\r\n");
      out.write("\r\n");
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
