/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-06-28 18:56:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.Random;

public final class SearchBus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Random");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1252\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write("  $( function() {\r\n");
      out.write("    $( \"#datepicker\" ).datepicker();\r\n");
      out.write("  } );\r\n");
      out.write(" </script>\r\n");
      out.write("<title>Book Tickets Now</title>\r\n");
      out.write("  <script LANGUAGE=\"Javascript\" SRC=\"Images/validate.js\"></script>\r\n");
      out.write("  <script LANGUAGE=\"Javascript\" SRC=\"Images/calender.js\"></script>\r\n");
      out.write("   <LINK href=\"styles.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write(" <SCRIPT LANGUAGE=\"JavaScript\">\r\n");
      out.write(" \r\n");
      out.write("	function setAction(URL,Obj){\r\n");
      out.write("		alert(\"Set action method is called \");\r\n");
      out.write("		var f = document.forms[0];\r\n");
      out.write("		var From = f.From.options[f.From.options.selectedIndex].text;\r\n");
      out.write("		//alert(From);\r\n");
      out.write("\r\n");
      out.write("		var To = f.To.options[f.To.options.selectedIndex].text;\r\n");
      out.write("		//alert(To);\r\n");
      out.write("		if(From==To){\r\n");
      out.write("			alert(\"From and To can not be same. Please select different places\");\r\n");
      out.write("			f.To.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		var JDate = f.JDate.value;\r\n");
      out.write("		//alert(JDate);\r\n");
      out.write("		if(JDate==\"\") {alert(\"Journey date is mandatory\");f.JDate.focus();return false;}\r\n");
      out.write("		if(validatePastDate(f.JDate)==false){\r\n");
      out.write("			alert(\"Past date is not allowed. Please select another date\");\r\n");
      out.write("			f.JDate.focus();return false;\r\n");
      out.write("		}\r\n");
      out.write("		var BusType = f.BusType.options[f.BusType.options.selectedIndex].text;\r\n");
      out.write("		//alert(BusType);\r\n");
      out.write("		var NoPass = f.NoPass.value;\r\n");
      out.write("		if(NoPass==\"\"||isNaN(NoPass)==true||NoPass<=0) {alert(\"Please enter a valid number for Number of passengers\");f.JDate.focus();return false;}\r\n");
      out.write("		//alert(NoPass);\r\n");
      out.write("		var ParamsList = \"?From=\"+From+\"&To=\"+To+\"&JDate=\"+JDate+\"&BusType=\"+BusType+\"&NoPass=\"+NoPass;\r\n");
      out.write("		Obj.target='tgt';\r\n");
      out.write("		Obj.href=URL+ParamsList;\r\n");
      out.write("	}\r\n");
      out.write(" \r\n");
      out.write(" </SCRIPT>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"SC\">\r\n");
      out.write("\r\n");
      out.write("<!-- <FORM ACTION=\"\"> -->\r\n");
      out.write("<form action = \"Search.jsp\" method = \"GET\">\r\n");
      out.write("\r\n");
      out.write("<p align=\"center\"><b><font face=\"Verdana\" color=\"#800080\" size=\"2\">Book Tickets \r\n");
      out.write("Now</font></b></p>\r\n");
      out.write("<div align=\"left\">\r\n");
      out.write("			<table align=\"center\">\r\n");
      out.write("				<tr class=\"row_odd\">\r\n");
      out.write("					<td>From</td>\r\n");
      out.write("					<td><SELECT NAME=\"From\" class=\"ListBox\">\r\n");
      out.write("							");

							Connection con = null;
							ResultSet res_set = null;
							Statement stmt = null;
							try {
								con = com.ewheelz.ConnectionPool.getConnection();
								stmt = con.createStatement();
								String qry = "select distinct rFrom from `routemaster`";
								res_set = stmt.executeQuery(qry);
								while (res_set.next()) {
							    
      out.write("\r\n");
      out.write("							      <option>");
      out.print(res_set.getString(1));
      out.write("</option>\r\n");
      out.write("							    ");
	
							      }
							} catch (Exception e) {
								
							}
							stmt.close();
							con.close();
                          
      out.write("\r\n");
      out.write("					</select></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"row_even\">\r\n");
      out.write("					<td>To</td>\r\n");
      out.write("					<td><SELECT NAME=\"To\" class=\"ListBox\">\r\n");
      out.write("								");

							Connection con1 = null;
							ResultSet res_set1 = null;
							Statement stmt1 = null;
							try {
								con1 = com.ewheelz.ConnectionPool.getConnection();
								stmt1 = con1.createStatement();
								String qry1 = "select distinct rTo from `routemaster`";
								res_set1 = stmt1.executeQuery(qry1);
								while (res_set1.next()) {
							    
      out.write("\r\n");
      out.write("							      <option>");
      out.print(res_set1.getString(1));
      out.write("</option>\r\n");
      out.write("							    ");
	
							      }
							} catch (Exception e) {
								
							}
							stmt1.close();
							con1.close();
                          
      out.write("\r\n");
      out.write("					</SELECT></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"row_odd\">\r\n");
      out.write("					<td>Journey Date</td>\r\n");
      out.write("					<!--     <td><input type=\"text\" name='JDate' data-role=\"date\" data-inline=\"true\"></td> -->\r\n");
      out.write("					<td><input type=\"text\" name='JDate' id=\"datepicker\"></td>\r\n");
      out.write("					<!-- <td><Input type=text name='JDate' value='' readonly size=\"12\"  class=\"TextField\">\r\n");
      out.write("			<img onkeypress=\"fnCalendar(this)\" id=\"imgDate\" style=\"CURSOR: hand\" onClick=\"fnCalendar(this)\" height=\"16\" src=\"Images/CalDis.gif\" width=\"16\" border=\"0\" name=\"imgDate\" onMouseOver=\"fnEnableCalLookup(this)\" onMouseOut=\"fnDisableCalLookup(this)\" ></td> -->\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"row_even\">\r\n");
      out.write("					<td>Bus Type</td>\r\n");
      out.write("					<td><SELECT NAME=\"BusType\" class=\"ListBox\">\r\n");
      out.write("							<OPTION>Sleeper</OPTION>\r\n");
      out.write("							<OPTION>AC</OPTION>\r\n");
      out.write("							<OPTION>Non AC</OPTION>\r\n");
      out.write("							<OPTION selected=\"selected\">any</OPTION>\r\n");
      out.write("					</SELECT></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"row_odd\">\r\n");
      out.write("					<td>No. of Passengers</td>\r\n");
      out.write("					<td><INPUT TYPE=\"text\" NAME=\"NoPass\" size=\"12\"\r\n");
      out.write("						class=\"TextField\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr class=\"row_even\">\r\n");
      out.write("					<td>&nbsp;</td>\r\n");
      out.write("					<td><input type=\"submit\" value=\"Check Availability\" /></td>\r\n");
      out.write("					<!-- <td><A onclick=\"setAction('Search.jsp',this)\" target=\"ResultFrame\"><IMG SRC=\"Images/Menu/chkAvailability1.gif\" border=\"0\"\r\n");
      out.write("			onmouseout=\"this.src = 'Images/Menu/chkAvailability1.gif'\" \r\n");
      out.write("			onmouseover=\"this.src = 'Images/Menu/chkAvailability2.gif'\"></A></td> -->\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("</FORM>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
